authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Wrapper for PCRE2 Perl Compatible Regular Expression library"
keywords = ["Strings", "PCRE", "Regex"]
license = "MIT"
name = "PCRE2"
uuid = "c9310f65-a42c-5928-aca3-d34f64192029"
version = "1.1.0"

[deps]
PCRE2_jll      = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
Libdl          = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.7"
